### ISSUE TITLE
[Feature] Add Navbar of the Website

### ISSUE THREAD

**Issue by paardarshee** [gdsc-aec-india/GDSCAEC-WEBSITE#1]
Add Navbar of the Website. [UI Design](https://www.figma.com/file/L2GYK3G0lOmUj9Hsciqqar/GDSC-WEBSITE)
To - do's:-

- Make a New NavBar.jsx file in Components folder
- Use Barrel export
- Import it in App.jsx
- Use TailWindCSS

For using any other package or technique contact us over our Discord.

**Comment by mrshivamshaw** [comment]
I would like to work on this feature. Please assign me @TheCodeVenturer

**Comment by paardarshee** [comment]
Sure @shivamshaw07,

**Comment by mrshivamshaw** [comment]
@TheCodeVenturer Done
