### ISSUE TITLE
[Bug] website shows React App insted of website name in title 

### ISSUE THREAD

**Issue by vipulpandey7860** [gdsc-aec-india/GDSCAEC-WEBSITE#17]
### Contact Details

vipulpandey7860@gmail.com

### What happened?

A bug happened!

website shows React App insted of website name in title 

### Version

0.1.0rc (Default)

### Contribution Guidelines

- [X] I have gone through the contribution guidelines

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rajdips834** [comment]
Assign

**Comment by vipulpandey7860** [comment]
please assign this issue to me

**Comment by paardarshee** [comment]
Hey @I-VipulPandey, We are not accepting any issues created by someone other then maintainers
If you want to add some issue, What you can do is Join Our Discord Server and discuss about these there
