### ISSUE TITLE
[Feature] Add an our Team Section

### ISSUE THREAD

**Issue by paardarshee** [gdsc-aec-india/GDSCAEC-WEBSITE#5]
Add our Team Section of the Website. [UI Design](https://www.figma.com/file/L2GYK3G0lOmUj9Hsciqqar/GDSC-WEBSITE)
To - do's:-

- Make a New Team.jsx file in the Components folder
- Make another Member.jsx Component for handling each event [ If needed ]
- Use Barrel export
- Import it in App.jsx
- Use TailWindCSS

JSON file of the team details provided in the data folder

For using any other package or technique contact us over our Discord.

**Comment by SathvikKandadi** [comment]
Hey I am new to opensource can you assign me this issue?

**Comment by paardarshee** [comment]
Sure @SathvikKandadi 
Discuss about this issue on our Discord.

**Comment by paardarshee** [comment]
any update @SathvikKandadi ?
