### ISSUE TITLE
[Feature] Add Contact us Section

### ISSUE THREAD

**Issue by paardarshee** [gdsc-aec-india/GDSCAEC-WEBSITE#6]
Add Contact us Section of the Website. [UI Design](https://www.figma.com/file/L2GYK3G0lOmUj9Hsciqqar/GDSC-WEBSITE)
To - do's:-

- Make a New Contact.jsx file in Components folder
- Use Barrel export
- Import it in App.jsx
- Use TailWindCSS

For using any other package or technique contact us over our Discord.

**Comment by rajdips834** [comment]
Assign

**Comment by rajdips834** [comment]
Please close this issue
