### ISSUE TITLE
[Feature] Add Organisation Footer Section

### ISSUE THREAD

**Issue by paardarshee** [gdsc-aec-india/GDSCAEC-WEBSITE#7]
Add a Footer of the Website. [UI Design](https://www.figma.com/file/L2GYK3G0lOmUj9Hsciqqar/GDSC-WEBSITE)
To-do's:-

- Make a New Footer.jsx file in the Components folder
- Use Barrel export
- Import it in App.jsx
- Use TailWindCSS

For using any other package or technique contact us over our Discord.

**Comment by Snowfall22** [comment]
Would like to work on this, please assign it to me

**Comment by paardarshee** [comment]
sure @Snowfall22 ,

**Comment by rajdips834** [comment]
Assign if not done

**Comment by paardarshee** [comment]
> Assign if not done

sure @rajdips834,

**Comment by paardarshee** [comment]
Hey @Snowfall22, may I inquire why you removed your assignment within just two hours of being assigned?

**Comment by Snowfall22** [comment]
> Hey @Snowfall22, may I inquire why you removed your assignment within just two hours of being assigned?

was caught up with other work so wasn't sure if I would have the time. I'll definitely be on the lookout for other issues I could help in.

**Comment by rajdips834** [comment]
Created a Pull request please review
