### ISSUE TITLE
Improve the project README & CONTRIBUTING.md

### ISSUE THREAD

**Issue by paardarshee** [gdsc-aec-india/GDSCAEC-WEBSITE#8]
- use this [Link](https://github.com/gdsc-aec-india/branding) in Readme files.
- Add Project Setup Instruction
- Remove irrelevant content

For more details connect us over our Discord.

**Comment by Snowfall22** [comment]
interested

**Comment by paardarshee** [comment]
@Snowfall22 
Do you want to be assigned?
and work on the issue

**Comment by priyanshu9899** [comment]
assign me , i would love to work on this

**Comment by paardarshee** [comment]
Sure @priyanshu9899,
Discuss in this thread or over our discord

**Comment by priyanshu9899** [comment]
sure

**Comment by priyanshu9899** [comment]
@TheCodeVenturer can you provide me the discord link because the one on the readme file is not working

**Comment by paardarshee** [comment]
> @TheCodeVenturer can you provide me the discord link because the one on the readme file is not working 
> 

Thanks @priyanshu9899 for notifying, 

Here is the updated [Link](https://discord.com/invite/DPAAtsHW)
